### ISSUE TITLE
solicitud de ayuda

### ISSUE THREAD

**Issue by ramonrxven** [alromh87/pyMorphoILV#1]
Estimado Alejandro,
estoy desarrollando una funcionalidad en python donde tengo que enrolar y verificar una huella dactilar,
me conseguí con este proyecto tuyo, ya que precisamente estoy usando un dispositivo SAGEM, y entre mis escasos conocimientos en biometría y que  este fabricante solo tiene SDK propietario para windows, pues me han puesto el proyecto cuesta arriba.
En el punto en el que me encuentro actualmente he podido  usar con éxito tu código para leer las huellas, sin embargo, no tengo conocimientos en materia de comparar las huellas y enrolarlas y estoy atascado,
quise acudir a ti a ver si es posible que me ayudes sobre como puedo resolver estos requerimientos,
disculpa el abuso de confianza,
agradecido de antemano
Ramon Archer.  ramonrxven arroba gmail punto com

**Comment by alromh87** [comment]
No es abuso, justo eso es lo bello del software libre:
   "El conocimiento compartido crece!!!"

Veo dos opciones inmediatas para ti:

## Utilizar el lector para hacer la comparación
    Cada lector puede almacenar huellas y realizar comparaciones ya sea verificación(1:1) o identificación(1:n).
- Ventajas:
  - Sencillo -> ya esta todo en el lector
- Desventajas:
  -  Atado a un proveedor
  - Huellas en cada dispositivo
  - No muy escalable
  - Costos variables de acuerdo con número de consultas

Este método puede hacerse mediante mensajes ILV, como se documenta en *MorphoSmart™ Host System Interface specifications*, por cuestiones de tiempo y prioridades no esta implementado en esta librería, si lo haces por favor haz un Pull Request.

##Construir sobre el motor biométrico del NIST, "[NBIS](https://www.nist.gov/services-resources/software/nist-biometric-image-software-nbis)"

- Ventajas:
  - Sencillo -> ya esta todo en el lector
  -  Independencia de proveedor
  - Se pueden diseñar esquemas de verificación, identificación local o centralizado
  - Facilménte escalable
  - Sin costos extras
  - Mayor aprendizaje de la tecnología

- Desventajas:
  - Casi pongo ninguna: Quizá solo la restricción de exportación si tu país esta en la lista negra de USA.

Estas librerías fueron desarrolladas originalmente para C en *Nix pero el NIST publicó wrappers para .NET y yo las he utilizado desde python y Java(JNI) desde Android.

- El wrapper para python puedes encontrarlo en [NBIS-python](https://github.com/alromh87/NBIS-python), en proximos dias liberare mayor funcionalidad, estas son las funicones implementadas/ en desarrollo:
  - [x] NFIQ: Evaluar calidad de las huellas
  - [x] WSQ: Comprimir a estandar de huellas "WSQ"
  - [ ] MINDTCT: Extraer minucias
  - [ ] BOZORTH: Comparar huellas

- En el caso de JAVA no lo he publicado pero esta en mi lista de pendientes

Recomiendo la segunda opción pues te dará independencia, aprendizaje y gobernabilidad, ten cuidado solo de los esquemas de seguridad que implementes.
